### 1. 넘파이를 사용하여 다음과 같은 행렬을 만드시오.
10 20 30 40

50 60 70 80

In [2]:
import numpy as np

In [4]:
np.arange(10, 81, 10).reshape(2, -1)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### 2. 다음 행렬과 같은 행렬이 있다.

In [55]:
m = np.arange(0, 15).reshape(3, -1)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [56]:
# 이 행렬에서 값 7을 인덱싱
m[1, 2]

7

In [57]:
# 이 행렬에서 값 14를 인덱싱
m[2, 4]

14

In [58]:
# 이 행렬에서 배열 [6, 7]을 슬라이싱
m[1, 1:3]

array([6, 7])

In [59]:
# 이 행렬에서 배열 [7, 12]를 슬라이싱
m[-2:, 2]

array([ 7, 12])

In [60]:
# 이 행렬에서 배열 [[3, 4], [8, 9]]를 슬라이싱
m[0:2, -2:]

array([[3, 4],
       [8, 9]])

### 3. 2번의 행렬 m을 1차원 벡터 f로 변환한 후 다음의 문제를 푸시오 

In [61]:
f = m.flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [62]:
# 이 배열에서 3의 배수를 찾아라
index = np.where(f % 3 == 0)
f.take(index)

array([[ 0,  3,  6,  9, 12]])

In [67]:
# 이 배열에서 4로 나누면 1이 남는 수를 찾아라
index = np.where(f % 4 == 1)
f.take(index)

array([[ 1,  5,  9, 13]])

In [76]:
# 이 배열에서 3으로 나누면 나누어지고 4로 나누면 이 남는 수를 찾아라
index1 = np.logical_and(f % 3 == 0, f%4==1)
index2 = np.where(index1 == True)
f.take(index2)

array([[9]])

### 4. 값을 직접 입력하지 말고 행렬을 만드시오

In [84]:
np.eye(5, 5) * 2  + np.eye(5, 5, 1) * 1 + np.eye(5, 5, -1) * 3

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

### 5. 0에서 10까지 랜덤 실수값으로 이루어진 5x6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구하시오

In [98]:
# matrix = np.random.uniform(0, 10, 30).reshape(5, 6)
matrix = np.random.randint(0, 10, 30).reshape(5, 6)
matrix

array([[1, 8, 2, 2, 8, 0],
       [0, 4, 2, 7, 7, 8],
       [6, 1, 8, 7, 2, 4],
       [1, 4, 1, 0, 9, 1],
       [2, 9, 2, 9, 6, 9]])

In [99]:
# 전체의 최댓값
np.max(matrix)

9

In [100]:
# 각 행의 합
matrix.sum(axis=1)

array([21, 28, 28, 16, 37])

In [102]:
# 각 열의 평균
np.average(matrix, axis=0)

array([2. , 5.2, 3. , 5. , 6.4, 4.4])

In [107]:
# 각 열의 최솟값
np.min(matrix, axis=0), matrix.min(axis=0)

(array([0, 1, 1, 0, 2, 0]), array([0, 1, 1, 0, 2, 0]))

### 6. 다음 배열은 첫 번째 행(row)에 학번, 두 번째 행에 영어성적, 세번째 행에 수학성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하시오

In [145]:
matrix = np.array([[ 1,  2,   3,   4],
                   [46, 99, 100,  71],
                   [81, 59,  90, 100]])

In [146]:
vec1 = matrix[0][[0, 3, 1, 2]]
vec2 = matrix[1][[0, 3, 1, 2]]
vec3 = matrix[2][[0, 3, 1, 2]]
np.vstack((vec1, vec2, vec3))

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [148]:
s = np.argsort(matrix[1])
s

array([0, 3, 1, 2])

In [149]:
matrix[:, s[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

### 7. 주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 던져서 나오는 숫자의 평균을 구하시오

In [119]:
dice = np.random.randint(1, 7, 100).reshape(10, -1)
print(dice)
np.average(dice)

[[1 2 4 3 6 5 2 4 3 3]
 [6 3 5 2 4 6 4 3 3 4]
 [3 3 4 5 4 4 5 1 5 5]
 [1 5 2 2 5 1 4 4 2 5]
 [1 6 1 6 3 4 3 4 2 1]
 [2 1 2 3 4 3 2 5 2 1]
 [2 3 1 6 1 4 1 3 6 5]
 [4 6 4 4 3 1 6 5 2 2]
 [2 2 1 4 4 6 2 6 1 1]
 [6 2 4 2 5 3 6 1 6 4]]


3.36

### 8. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하시오.